### ISSUE TITLE
Issue with density and ambient.Profile.extend_profile_deeper() and density

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [socolofs/tamoc#25]
I have created a profile with data down to 260 m, and then call:

`profile.extend_profile_deeper(300.)`

then plot: `profile.plot_profiles(['temperature', 'salinity', 'density', 'ua', 'oxygen'])`
which results in:
![Profile_fig_density_bug](https://github.com/socolofs/tamoc/assets/916576/bfd9bc3c-7118-47ab-840d-6bbca19db10e)

Note that density looks wonky below 250

I'm also confused as to why density is going down when temp is gong down and salinity going up ??

**Comment by socolofs** [comment]
That definitely does not look right.  It is working for me on the data you sent me.  I get this:

[cid:396D2E4B-5E42-473E-AA65-3233ECB7E786]

The plot method calls “ambient.BaseProfile.insert_density().  I would add print statements there to find out what T, S, and P data are being used.  Something is getting crossed.  T must be in Kelvin, S in psu, and P in Pascal.

Otherwise, this looks right.

TAMOC doesn’t actually use this density profile.  It always computed density from T, S, and P.  So, if those parameters are right, it will work.  Try plotting the pressure and make sure it looks right.

Headed offline for a week.  Good Luck!

Scott



-----------
Scott A. Socolofsky,
J. Walter “Deak” Porter ’22 and James W. “Bud” Porter ’51 Chair,
Zachry Department of Civil and Environmental Engineering
Department of Oceanography
Department of Ocean Engineering
Texas A&M University
(979) 845-4517
-----------

On Jul 21, 2023, at 6:40 PM, Chris Barker ***@***.******@***.***>> wrote:

This Message Is From an External Sender
This message came from outside your organization.


I have created a profile with data down to 260 m, and then call:

profile.extend_profile_deeper(300.)

then plot: profile.plot_profiles(['temperature', 'salinity', 'density', 'ua', 'oxygen'])
which results in:
[Profile_fig_density_bug]<https://urldefense.com/v3/__https://user-images.githubusercontent.com/916576/255299638-bfd9bc3c-7118-47ab-840d-6bbca19db10e.png__;!!KwNVnqRv!C3f9eOJib6FEB7XCRZzolN8CobYIrxLzyWHKSdmYpJ_wSWACM_-bEXZdFZ6TR1QP3HciQKvbE3TNZUlEGAe6IKJtLQ$>

Note that density looks wonky below 250

I'm also confused as to why density is going down when temp is gong down and salinity going up ??

**Comment by ChrisBarker-NOAA** [comment]
I figured it out -- I hadn't supplied pressure, to it was computing the pressure profile. However, the code assumes K, and I had supplied temp in C. It does convert to standard units, but not until after it computes the pressure profile -- the properties of water at 15K are pretty stange :-)

I've fixed this in this now a bit crowded PR: #24
